/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vuepress-template",
  "description": "template",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/assets/images/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "语法",
      "frontmatter": {},
      "regularPath": "/api/",
      "relativePath": "api/index.md",
      "key": "v-7dfc924e",
      "path": "/api/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/robot-solid.svg",
        "heroText": null,
        "tagline": "template",
        "actionText": "快速上手 →",
        "actionLink": "/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-15a2a339",
      "path": "/"
    },
    {
      "title": "其他",
      "frontmatter": {},
      "regularPath": "/guide/others.html",
      "relativePath": "guide/others.md",
      "key": "v-156b8ff5",
      "path": "/guide/others.html"
    },
    {
      "title": "简介",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-0ace694c",
      "path": "/guide/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "API",
        "link": "/api/"
      }
    ],
    "repo": "sibenmao/vuepress-template",
    "sidebar": {
      "/guide/": [
        "",
        "others"
      ],
      "/api/": [
        ""
      ]
    }
  }
}